common_fields:
  cash_equivalents:
    chinese_name: 货币资金
    field_name: CASH
    table: balance_sheet
  earnings:
    chinese_name: 扣除非经常性损益后的净利润
    field_name: DEDUCTEDPROFIT
    table: income_statement
  equity:
    chinese_name: 归属于母公司股东权益合计
    field_name: EQY_BELONGTO_PARCOMSH
    table: balance_sheet
  financial_expense:
    chinese_name: 财务费用
    field_name: FIN_EXP_IS
    table: income_statement
  operating_cash_flow:
    chinese_name: 经营活动产生的现金流量净额
    field_name: NETCASH_OPER
    table: cash_flow
  quarter:
    chinese_name: 季度
    field_name: d_quarter
    table: auxiliary
  revenue:
    chinese_name: 营业总收入
    field_name: TOT_OPER_REV
    table: income_statement
  short_term_debt:
    chinese_name: 短期借款
    field_name: ST_BORROW
    table: balance_sheet
field_descriptions:
  balance_sheet:
    fields:
      ACCT_PAYABLE: 应付账款
      ACCT_RCV: 应收账款
      ACC_EXP: 预提费用
      ACTING_TRADING_SEC: 代理买卖证券款
      ACTING_UW_SEC: 代理承销证券款
      ADV_FROM_CUST: 预收账款
      AGENCY_BUS_ASSETS: 代理业务资产
      AGENCY_BUS_LIAB: 代理业务负债
      ASSET_DEP_OTH_BANKS_FIN_INST: 存放同业和其他金融机构款项
      BONDS_PAYABLE: 应付债务
      BORROW_CENTRAL_BANK: 向中央银行借款
      CAP_MRGN_PAID: 存出资本保证金
      CAP_RSRV: 资本公积金
      CAP_STK: 实收资本（或股本）
      CASH_DEPOSITS_CENTRAL_BANK: 现金及存放中央银行款项
      CLAIMS_PAYABLE: 应付赔付款
      CLIENTS_CAP_DEPOSIT: 客户资金存款
      CLIENTS_RSRV_SETTLE: 客户备付金
      CNVD_DIFF_FOREIGN_CURR_STAT: 外币报表折算差额
      CONST_IN_PROG: 在建工程
      CONSUMPTIVE_BIO_ASSETS: 消耗性生物资产
      CUST_BANK_DEP: 吸收存款
      DEFERRED_EXP: 待摊费用
      DEFERRED_INC_CUR_LIAB: 递延收益-流动负债
      DEFERRED_INC_NON_CUR_LIAB: 递延收益-非流动负债
      DEFERRED_TAX_ASSETS: 递延所得税资产
      DEFERRED_TAX_LIAB: 递延所得税负债
      DEPOSIT_RECEIVED: 存入保证金
      DEPOSIT_RECEIVED_IB_DEPOSITS: 吸收存款及同业存放
      DERIVATIVE_FIN_ASSETS: 衍生金融资产
      DERIVATIVE_FIN_LIAB: 衍生金融负债
      DVD_PAYABLE: 应付股利
      DVD_PAYABLE_INSURED: 应付保单红利
      DVD_RCV: 应收股利
      EMPL_BEN_PAYABLE: 应付职工薪酬
      EQY_BELONGTO_PARCOMSH: 归属母公司股东的权益
      FIN_ASSETS_AVAIL_FOR_SALE: 可供出售金融资产
      FIX_ASSETS: 固定资产
      FIX_ASSETS_DISP: 固定资产清理
      FUND_SALES_FIN_ASSETS_RP: 卖出回购金融资产款
      GOODWILL: 商誉
      HANDLING_CHARGES_COMM_PAYABLE: 应付手续费及佣金
      HELD_TO_MTY_INVEST: 持有至到期投资
      HFS_ASSETS: 划分为持有代售的资产
      HFS_LIAB: 划分为持有待售的负债
      INDEPENDENT_ACCT_ASSETS: 独立账户资产
      INDEPENDENT_ACCT_LIAB: 独立账户负债
      INSURED_DEPOSIT_INVEST: 保户储金及投资款
      INSURED_PLEDGE_LOAN: 保护质押贷款
      INTANG_ASSETS: 无形资产
      INT_PAYABLE: 应付利息
      INT_RCV: 应收利息
      INVENTORIES: 存货
      INVEST_REAL_ESTATE: 投资性房地产
      LIAB_DEP_OTH_BANKS_FIN_INST: 同业和其他金融机构存放款项
      LIFE_INSUR_RSRV: 寿险责任准备金
      LOANS_AND_ADV_GRANTED: 发放贷款及垫款
      LOANS_OTH_BANKS: 拆入资金
      LOANS_TO_OTH_BANKS: 拆出资金
      LONG_TERM_DEFERRED_EXP: 长期待摊费用
      LONG_TERM_EQY_INVEST: 长期股权投资
      LONG_TERM_REC: 长期应收款项
      LT_BORROW: 长期借款
      LT_EMPL_BEN_PAYABLE: 长期应付职工薪酬
      LT_HEALTH_INSUR_V: 长期健康限责任准备金
      LT_PAYABLE: 长期应付款
      MARGIN_ACCT: 融入资金
      MINORITY_INT: 少数股东权益
      MONETARY_CAP: 货币资金
      MRGN_PAID: 存出保证金
      NON_CUR_ASSETS_DUE_WITHIN_1Y: 一年内到期的非流动性资产
      NON_CUR_LIAB_DUE_WITHIN_1Y: 一年内到期的非流动负债
      NOTES_PAYABLE: 应付票据
      NOTES_RCV: 应收票据
      OIL_AND_NATURAL_GAS_ASSETS: 油气资产
      OTHER_COMPREH_INC_BS: 其他综合收益
      OTHER_EQUITY_INSTRUMENTS: 其他权益工具
      OTHER_EQUITY_INSTRUMENTS_PRE: 其他权益工具：优先股
      OTH_ASSETS: 其他资产
      OTH_CUR_ASSETS: 其他流动资产
      OTH_CUR_LIAB: 其他流动负债
      OTH_LIAB: 其他负债
      OTH_NON_CUR_ASSETS: 其他非流动性资产
      OTH_NON_CUR_LIAB: 其他非流动负债
      OTH_PAYABLE: 其他应付款
      OTH_RCV: 其他应收款
      OUT_LOSS_RSRV: 未决赔款准备金
      PAYABLE_TO_REINSURER: 应付分保账款
      PLEDGE_LOAN: 质押借款
      PRECIOUS_METALS: 贵金属
      PREM_RCV: 应收保费
      PREM_RECEIVED_ADV: 预收保费
      PREPAY: 预付款项
      PRODUCTIVE_BIO_ASSETS: 生产性生物资产
      PROJ_MATL: 工程物资
      PROVISIONS: 预计负债
      PROV_NOM_RISKS: 一般风险准备
      RCV_CEDED_CLAIM_RSRV: 应收分保未决赔款准备金
      RCV_CEDED_LIFE_INSUR_RSRV: 应收分保寿险责任准备金
      RCV_CEDED_LT_HEALTH_INSUR_RSRV: 应收分保长期健康限责任准备金
      RCV_CEDED_UNEARNED_PREM_RSRV: 应收分保未到期责任准备金
      RCV_FROM_CEDED_INSUR_CONT_RSRV: 应收分保合同准备金
      RCV_FROM_REINSURER: 应收分保账款
      RCV_INVEST: 应收款项类投资
      RED_MONETARY_CAP_FOR_SALE: 买入返售金融资产
      RSRV_INSUR_CONT: 保险合同准备金
      R_AND_D_COSTS: 开发支出
      SEAT_FEES_EXCHANGE: 交易席位费
      SETTLE_RSRV: 结算准备金
      SPECIAL_RSRV: 专项储备
      SPECIFIC_ITEM_PAYABLE: 专项应付款
      ST_BONDS_PAYABLE: 应付短期债券
      ST_BORROW: 短期借款
      ST_FINL_INST_PAYABLE: 应付短期融资款
      SUBR_REC: 应收代位追偿款
      SURPLUS_RSRV: 盈余公积金
      TAXES_SURCHARGES_PAYABLE: 应交税费
      TIME_DEPOSITS: 定期存款
      TOT_ACCT_PAYABLE: 应付款项
      TOT_ACCT_RCV: 应收款项
      TOT_ASSETS: 资产总计
      TOT_CUR_ASSETS: 流动资产合计
      TOT_CUR_LIAB: 流动负债合计
      TOT_EQUITY: 所有者权益合计
      TOT_LIAB: 负债合计
      TOT_LIAB_SHRHLDR_EQY: 负债及股东权益总计
      TOT_NON_CUR_ASSETS: 非流动资产合计
      TOT_NON_CUR_LIAB: 非流动负债合计
      TRADABLE_FIN_ASSETS: 以公允价值计量切变动计入当期损益的金融资产
      TRADABLE_FIN_LIAB: 以公允价值计量且其变动计入当期损益的全部负债
      TSY_STK: 减：库存股
      UNCONFIRMED_INVEST_LOSS_BS: 未确认的投资损失
      UNDISTRIBUTED_PROFIT: 未分配利润
      UNEARNED_PREM_RSRV: 未到期责任准备金
    name: 资产负债表
    name_en: Balance Sheet
  cash_flow:
    fields:
      AMORT_INTANG_ASSETS: 无形资产摊销
      AMORT_LT_DEFERRED_EXP: 长期待摊费用摊销
      BEG_BAL_CASH: 现金的期初余额
      BEG_BAL_CASH_EQU: 现金等价物的期初余额
      CASH_CASH_EQU_BEG_PERIOD: 期初现金及现金等价物余额
      CASH_CASH_EQU_END_PERIOD: 期末现金及现金等价物余额
      CASH_PAID_INVEST: 投资支付的现金
      CASH_PAY_ACQ_CONST_FIOLTA: 构建固定资产、无形资产和其他长期资产支付的现金
      CASH_PAY_BEH_EMPL: 支付给职工的以及为职工支付的现金
      CASH_PAY_CLAIMS_ORIG_INCO: 支付原保险合同赔付款项的现金
      CASH_PAY_DIST_DPCP_INT_EXP: 分配股利、利润和偿付利息所支出的现金
      CASH_PAY_GOODS_PURCH_SERV_REC: 购买商品、接受劳务支付的现金
      CASH_PREPAY_AMT_BORR: 偿还债务所支付的现金
      CASH_RECP_BORROW: 取得借款收到的现金
      CASH_RECP_CAP_CONTRIB: 吸收投资所受到的现金
      CASH_RECP_DISP_WITHDRWL_INVEST: 收回投资收到的现金
      CASH_RECP_PREM_ORIG_INCO: 收到的原保险合同保费取得的现金
      CASH_RECP_RETURN_INVEST: 取得投资收益收到的现金
      CASH_RECP_SG_AND_RS: 销售商品、提供劳务收到的现金
      CASH_REC_SAIMS: 子公司吸收少数股东投资收到的现金
      COMM_INSUR_PLCY_PAID: 支付保单红利的现金
      CONV_CORP_BONDS_DUE_WITHIN_1Y: 一年内到期的可转换公司债券
      CONV_DEBT_INTO_CAP: 债务转为资本
      DECR_DEFERRED_EXP: 待摊费用减少
      DECR_DEFERRED_INC_TAX_ASSETS: 递延所得税资产减少
      DECR_INVENTORIES: 存货减少
      DECR_OPER_PAYABLE: 经营性应收项目的减少
      DEPR_FA_COGA_DPBA: 固定资产折旧、油气资产折耗、生产性生物资产折旧
      DVD_PROFIT_PAID_SC_MS: 子公司支付给少数股东的股利、利润
      EFF_FX_FLU_CASH: 汇率变动对现金的影响
      END_BAL_CASH: 现金的期末余额
      END_BAL_CASH_EQU: 现金等价物的期末余额
      FA_FNC_LEASES: 融资租入固定资产
      FIN_EXP_CS: 财务费用
      HANDLING_CHRG_PAID: 支付手续费的现金
      IM_NET_CASH_FLOWS_OPER_ACT: 间接法-经营活动产生的现金流量净额
      INCR_ACC_EXP: 预计费用增加
      INCR_DEFERRED_INC_TAX_LIAB: 递延所得税负债增加
      INCR_OPER_PAYABLE: 经营性应付项目的增加
      INVEST_LOSS: 投资损失
      LOSS_DISP_FIOLTA: 处置固定资产、 无形资产和其他长期资产的损失
      LOSS_FV_CHG: 公允价值变动损失
      LOSS_SCR_FA: 固定资产报废损失
      NET_CASH_FLOWS_FNC_ACT: 筹资活动产生的现金流量净额
      NET_CASH_FLOWS_INV_ACT: 投资活动产生的现金流量净额
      NET_CASH_FLOWS_OPER_ACT: 经营活动产生的现金流量净额
      NET_CASH_FROM_SEURITIES: 代理买卖证券收到的现金净额
      NET_CASH_PAY_AQUIS_SOBU: 取得子公司及其他营业单位支付的现金净额
      NET_CASH_RECEIVED_REINSU_BUS: 收到的再保险业务现金净额
      NET_CASH_RECP_DISP_FIOLTA: 处置固定资产、无形资产和其他长期资产收回的现金净额
      NET_CASH_RECP_DISP_SOBU: 处置子公司及其他营业单位收到的现金净额
      NET_FINA_INSTRUMENTS_MEASURED_AT_FMV: 以公允价值计量且其变动计入当期损益的金融工具净额
      NET_INCR_CASH_CASH_EQU_DM: 现金及现金等价物净增加额
      NET_INCR_CASH_CASH_EQU_IM: 间接法-现金及现金等价物净增加额
      NET_INCR_CLIENTS_LOAN_ADV: 客户贷款及垫款净增加额
      NET_INCR_DEP_CBOB: 存放央行和同业款项净增加额
      NET_INCR_DEP_COB: 客户存款和同业存放款项净增加额
      NET_INCR_DISP_FIN_ASSETS_AVAIL: 处置可供出售金融资产增加额
      NET_INCR_DISP_TFA: 处置交易性金融资产净增加额
      NET_INCR_FUND_BORR_OFI: 向其他金融机构拆入资金净增加额
      NET_INCR_INSURED_DEP: 保户储金净增加额
      NET_INCR_INT_HANDLING_CHRG: 收取利息和手续费净增加额
      NET_INCR_LENDING_FUND: 融出资金净增加额
      NET_INCR_LOANS_CENTRAL_BANK: 向中央银行借款净增加额
      NET_INCR_LOANS_OTHER_BANK: 拆入资金净增加额
      NET_INCR_PLEDGE_LOAN: 质押贷款净增加额
      NET_INCR_REPURCH_BUS_FUND: 回购业务资金净增加额
      NET_PROFIT_CS: 净利润
      OTHERS: 其他
      OTHER_CASH_PAY_RAL_FNC_ACT: 支付的其他与筹资活动有关的现金
      OTHER_CASH_PAY_RAL_INV_ACT: 支付的其他与投资活动有关的现金
      OTHER_CASH_PAY_RAL_OPER_ACT: 支付的其他与经营活动有关的现金
      OTHER_CASH_RECP_RAL_FNC_ACT: 收到的其他与筹资活动有关的现金
      OTHER_CASH_RECP_RAL_INV_ACT: 收到的其他与投资活动有关的现金
      OTHER_CASH_RECP_RAL_OPER_ACT: 收到的其他与经营活动有关的现金
      PAY_ALL_TYP_TAX: 支付的各项税费
      PROC_ISSUE_BONDS: 发行债券收到的现金
      PROV_DEPR_ASSETS: 资产减值准备
      RECP_TAX_RENDS: 收到的税费返还
      STOT_CASH_INFLOWS_FNC_ACT: '筹资活动现金流入小计 '
      STOT_CASH_INFLOWS_INV_ACT: 投资活动现金流入小计
      STOT_CASH_INFLOWS_OPER_ACT: 经营活动现金流入小计
      STOT_CASH_OUTFLOWS_FNC_ACT: 筹资活动现金流出小计
      STOT_CASH_OUTFLOWS_INV_ACT: 投资活动现金流出小计
      STOT_CASH_OUTFLOWS_OPER_ACT: 经营活动现金流出小计
      UNCONFIRMED_INVEST_LOSS_CS: 未确定的投资损失
    name: 现金流量表
    name_en: Cash Flow Statement
  income_statement:
    fields:
      CLAIM_EXP_RECOVERABLE: 摊回赔付支出
      DEDUCTEDPROFIT: 扣非净利润
      DVD_EXP_INSURED: 保单红利支出
      EPS_BASIC_IS: 基本每股收益
      EPS_DILUTED_IS: 稀释每股收益
      FIN_EXP_IS: 财务费用
      GERL_ADMIN_EXP: 管理费用
      HANDLING_CHRG_COMM_EXP: 手续费及佣金支出
      HANDLING_CHRG_COMM_INC: 手续费及佣金收入
      IMPAIR_LOSS_ASSETS: 资产减值损失
      INC_INVEST_ASSOC_JV_ENTP: 对联营企业和合营企业的投资收益
      INSUR_PREM_UNEARNED: 已赚保费
      INSUR_RSRV_RECOVERABLE: 摊回保险责任准备金
      INT_EXP: 利息支出
      INT_INC: 利息收入
      MINORITY_INT_INC: 少数股东损益
      NET_CLAIM_EXP: 赔付支出
      NET_FEE_AND_COMMISSION_INC: 手续费及佣金净收入
      NET_GAIN_CHG_FV: 公允价值变动的净收益
      NET_GAIN_FX_TRANS: 汇兑净收益
      NET_INC_AGENCYBUSINESS: 代理买卖证券业务净收入
      NET_INC_CUSTOMERASSET-MANAGEMENTBUSINESS: 委托客户资产管理业务净收入
      NET_INC_OTHER_OPS: 其他经营净收入
      NET_INC_UNDERWRITING-BUSINESS: 证券承销业务净收入
      NET_INSUR_CONT_RSRV: 提取保险责任准备金
      NET_INT_INC: 利息净收入
      NET_INVEST_INC: 投资净收益
      NET_LOSS_DISP_NONCUR_ASSET: 非流动资产处置净损失
      NET_OTHER_OPER_INC: 其他业务净收益
      NET_PROFIT_IS: 净利润
      NON_OPER_EXP: 营业外支出
      NON_OPER_REV: 营业外收入
      NP_BELONGTO_PARCOMSH: 归属母公司股东的净利润
      OPER_COST: 营业成本
      OPER_EXP: 营业支出
      OPER_REV: 营业收入
      OPPROFIT: 营业利润
      OTHER_COMPREH_INC: 其他综合收益
      OTHER_GRANTS_INC: 其他收益
      OTHER_OPER_EXP: 其他业务成本
      OTHER_OPER_INC: 其他业务净收入
      PREM_CEDED: 分出保费
      PREPAY_SURR: 退保金
      REINSURANCE_EXP: 分保费用
      REINSUR_EXP_RECOVERABLE: 摊回分保费用
      REINSUR_INC: 分保费收入
      SELLING_DIST_EXP: 销售费用
      STMNOTE_AUDIT_CATEGORY: 审计意见
      STMNOTE_INAUDIT_CATEGORY: 审计意见2
      TAX: 所得税
      TAXES_SURCHARGES_OPS: 税金及附加
      TOT_COMPREH_INC: 综合收益总额
      TOT_COMPREH_INC_MIN_SHRHLDR: 归属于少数股东的综合收益总额
      TOT_COMPREH_INC_PARENT_COMP: 归属于母公司普通股东综合收益总额
      TOT_OPER_COST: 营业总成本
      TOT_OPER_REV: 营业总收入
      TOT_PREM_INC: 保费业务收入
      TOT_PROFIT: 利润总额
      UNCONFIRMED_INVEST_LOSS_IS: 未确认的投资损失
      UNEARNED_PREM_RSRV_WITHDRAW: 提取未到期责任准备金
    name: 利润表
    name_en: Income Statement
table_attribution:
  ACCT_PAYABLE: fzb
  ADV_FROM_CUST: fzb
  CASH_PAY_GOODS_PURCH_SERV_REC: xjlb
  CASH_RECP_SG_AND_RS: xjlb
  DEDUCTEDPROFIT: lrb
  EQY_BELONGTO_PARCOMSH: fzb
  GOODWILL: fzb
  INVEST_LOSS: xjlb
  NET_CASH_FLOWS_OPER_ACT: xjlb
  NET_PROFIT_IS: lrb
  NP_BELONGTO_PARCOMSH: lrb
  OPER_COST: lrb
  OPER_EXP: lrb
  OPER_REV: lrb
  OPPROFIT: lrb
  OTHER_CASH_RECP_RAL_OPER_ACT: xjlb
  STMNOTE_AUDIT_CATEGORY: lrb
  STMNOTE_INAUDIT_CATEGORY: lrb
  STOT_CASH_INFLOWS_OPER_ACT: xjlb
  STOT_CASH_OUTFLOWS_OPER_ACT: xjlb
  TOT_COMPREH_INC_PARENT_COMP: lrb
  TOT_EQUITY: fzb
  TOT_OPER_COST: lrb
  TOT_OPER_REV: lrb
